### ISSUE TITLE
Improve the support of pypy in matrix-based analyzers

### ISSUE THREAD

**Issue by ateska** [LibertyAces/BitSwanPump#29]
A recent refactoring broken the pypy support.
It should be relatively easy to fix that.

**Comment by hrabalp** [comment]
following errors are poping up when used with pypy
`BitSwan BSPump version 18.10-dev-623-g2b93275
Traceback (most recent call last):
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/bspump/matrix.py", line 122, in add_row
    return self.ClosedRows.pop()
KeyError: 'pop from an empty set'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/pumpy/RADIUS/RadiusProcessing.py", line 90, in <module>
    app = Application()
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/asab/abc/singleton.py", line 14, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/var/pumpy/RADIUS/RadiusProcessing.py", line 85, in __init__
    service.add_pipeline(RadiusFixMainPipeline(self, 'RadiusFixMainPipeline', RadiusDict))
  File "/var/pumpy/RADIUS/RadiusProcessing.py", line 42, in __init__
    custommodules.RadiusTWA(app, self),
  File "/var/pumpy/RADIUS/custommodules/RadiusTWA.py", line 18, in __init__
    self.TimeWindow.HotColumnRowID = self.TimeWindow.add_row('HOT_COLUMN')
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/bspump/analyzer/timewindowmatrix.py", line 110, in add_row
    row_index = super().add_row(row_name)
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/bspump/matrix.py", line 193, in add_row
    row_index = super().add_row()
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/bspump/matrix.py", line 124, in add_row
    self._grow_rows(max(5, int(0.10 * self.Array.shape[0])))
  File "/root/pypy3.6-7.1.1-beta-linux_x86_64-portable/site-packages/bspump/matrix.py", line 144, in _grow_rows
    self.Array.resize((current_rows+rows,) + self.Array.shape[1:])
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False`

**Comment by SukiCZ** [comment]
@ateska is adding `refcheck=False` enough? If so we can close this issue (I was fixing unit-tests for `Python 3.7.1` which had the same one)

**Comment by ateska** [comment]
I guess so.

**Comment by ateska** [comment]
@SukiCZ ^^^

**Comment by SukiCZ** [comment]
Closing in favor of a8ec101
