### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [LibertyAces/BitSwanPump#68]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 20.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary bspump-utils -w /tmp/ext bspump-utils==20.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting bspump-utils==20.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/83a/b8bb65ca3d09a/bspump-utils-20.1.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-f7rdocck/bspump-utils/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-f7rdocck/bspump-utils/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-f7rdocck/bspump-utils/pip-egg-info
         cwd: /tmp/pip-wheel-f7rdocck/bspump-utils/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-f7rdocck/bspump-utils/setup.py", line 24, in <module>
        txt = (here / 'bspump' / '__version__.py').read_text('utf-8')
      File "/usr/lib/python3.8/pathlib.py", line 1227, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/lib/python3.8/pathlib.py", line 1213, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-f7rdocck/bspump/__version__.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ateska** [comment]
Solved in https://github.com/LibertyAces/BitSwanPump/commit/0fd7dc0fd9db7e77c5e1e3432f4685e1493db44d
